import {
  LayoutDashboard,
  FileText,
  FolderOpen,
  Upload,
  BarChart2,
  Settings,
  User,
  LogOut,
  Edit,
  Eye,
  MessageSquare,
  Search,
  Bold,
  Italic,
  Strikethrough,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  Quote,
  AlignRight,
  AlignCenter,
  AlignLeft,
  Trash2,
  Loader2,
  Info,
  Microscope,
  Scale,
  History,
  Mail,
  Lock,
  Share,
  Clock,
  type Icon as LucideIcon,
} from 'lucide-react'

export type Icon = typeof LucideIcon

export const Icons = {
  logo: FileText,
  dashboard: LayoutDashboard,
  post: FileText,
  category: FolderOpen,
  media: Upload,
  analytics: BarChart2,
  settings: Settings,
  user: User,
  logout: LogOut,
  edit: Edit,
  view: Eye,
  comment: MessageSquare,
  search: Search,
  bold: Bold,
  italic: Italic,
  strikethrough: Strikethrough,
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  list: List,
  listOrdered: ListOrdered,
  quote: Quote,
  alignRight: AlignRight,
  alignCenter: AlignCenter,
  alignLeft: AlignLeft,
  trash: Trash2,
  spinner: Loader2,
  info: Info,
  science: Microscope,
  law: Scale,
  history: History,
  mail: Mail,
  lock: Lock,
  share: Share,
  clock: Clock,
} 